import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import SideBar from "@/components/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="container flex">
            <SideBar />
            <div className="sticky top-[10vh] hidden md:flex h-[90vh] w-[3px] bg-accent mx-8"/>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
